<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\BeachBot.Core\BeachBot.Core.csproj" />
    <ProjectReference Include="..\BeachBot.Api\BeachBot.Api.csproj" />
    <ProjectReference Include="..\BeachBot.Application\BeachBot.Application.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

</Project>
